export * from "./Home/home.page"
export * from "./AboutUs/about-us.page"
export * from './singlePageProduct/singleProduct.page'
export * from './products/products.page'
export * from './login/login.page'
export * from './registeration/register.page'
export * from './pay/pay.page'
export * from './control/control.page'
export * from './payment-status/payment-status.page'
export * from './basket/basket.page'
export * from './shoppingPortal/shoppingPortal.page'